import { describe, it } from "node:test";
import assert from "node:assert/strict";
import { anonymizeDiff, assignmentFor, totalScore, validateReview } from "../benchmark_runs/blind_review_policy.mjs";

describe("blind review policy", () => {
  it("uses a deterministic balanced-looking anonymous assignment", () => {
    const first = assignmentFor("T01");
    assert.deepEqual(first, assignmentFor("T01"));
    assert.notEqual(first.X, first.Y);
    const xVariants = Array.from({ length: 10 }, (_, index) => assignmentFor(`T${String(index + 1).padStart(2, "0")}`).X);
    assert.ok(new Set(xVariants).size === 2, "both variants appear as X");
  });

  it("rejects identity leakage and shuffles complete diff sections", () => {
    assert.throws(() => anonymizeDiff("+ generated by codex-capsule", "T01", "X"), /leaks/);
    const diff = "diff --git a/b.ts b/b.ts\n+B\ndiff --git a/a.ts b/a.ts\n+A\n";
    const output = anonymizeDiff(diff, "T02", "Y");
    assert.match(output, /diff --git a\/a\.ts/);
    assert.match(output, /diff --git a\/b\.ts/);
  });

  it("validates bounded scores and computes the total", () => {
    const solution = {
      correctness: 5,
      coverage: 4,
      simplicity: 3,
      maintainability: 4,
      regressionSafety: 5,
      strengths: ["bounded"],
      fatalFlaws: [],
    };
    const review = validateReview({
      schemaVersion: 1,
      taskId: "T03",
      preference: "X",
      confidence: 0.8,
      solutions: { X: solution, Y: { ...solution, correctness: 4 } },
      rationale: "X covers cleanup.",
      requiredFollowups: [],
    }, "T03");
    assert.equal(totalScore(review.solutions.X), 21);
    assert.throws(() => validateReview({ ...review, confidence: 2 }, "T03"), /confidence/);
  });
});
